language: java

sudo: false
dist: trusty

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- java -version
- export GRADLE_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.io=ALL-UNNAMED"
# - export GRADLE_OPTS="--permit-illegal-access" # not supported in b162, yet
- ./gradlew -version

#
#  Hot-swap Groovy version to 2.4.10 (replacing 2.4.7) in local Gradle 3.4.1 installation
#
- wget http://repo1.maven.org/maven2/org/codehaus/groovy/groovy-all/2.4.10/groovy-all-2.4.10.jar
- rm /home/travis/.gradle/wrapper/dists/gradle-3.4.1-bin/71zneekfcxxu7l9p7nr2sc65s/gradle-3.4.1/lib/groovy-all-2.4.7.jar
- cp groovy-all-2.4.10.jar /home/travis/.gradle/wrapper/dists/gradle-3.4.1-bin/71zneekfcxxu7l9p7nr2sc65s/gradle-3.4.1/lib/groovy-all-2.4.7.jar

script:
- ./gradlew --no-daemon check
